- Dockerfile
- postman/Sila API v0.2 - Local Signer Server Edition.postman_collection.json
- signerserver/application.py
- signerserver/request_transform.py
Adds /documents endpoint to current Postman requests offering and handles signing of multipart/form-data content-types through the signer.
> Support document upload

- postman/Sila API v0.2 - Local Signer Server Edition.postman_collection.json
Adds additional endpoints to be tracked in the Postman collection.
Original work credited to @ArcGate-Vinod .
Original JIRA ticket link: https://sila.atlassian.net/browse/SILA-1374
> SILA-1374: Add /delete_wallet, /cancel_transaction, /get_sila_balance

- postman/Sila API v0.2 - Local Signer Server Edition.postman_collection.json
> Added new APIs to Postman

- postman/Sila API v0.2 - Local Signer Server Edition.postman_collection.json
Postman updates for /plaid_update_link_token new endpoin
> SILA-1694: Postman updates for /plaid_update_link_token new endpoin

- postman/Sila API v0.2 - Local Signer Server Edition.postman_collection.json
Added new param(plaid_token_type) to /link_account
> SILA-1900: Added new param(plaid_token_type) to /link_account

- signerserver/application.py
BUG- Sila Signer Server- removed the order field from the query string
> SILA-1932 : BUG- Sila Signer Server- removed the order field from query string

- postman/Sila API v0.2 - Local Signer Server Edition.postman_collection.json
Add /get_institutions endpoints to Postman collection
> SILA-1742 : Add /get_institutions endpoints to Postman collection

- postman/Sila API v0.2 - Local Signer Server Edition.postman_collection.json
- postman/SilaSandbox.postman_environment.json
Update Postman for various account endpoints for consistency and accuracy
> SILA-1920: Update Postman for various account endpoints for consistency and accuracy

- postman/Sila API v0.2 - Local Signer Server Edition.postman_collection.json
- Added a new search filter param by the wallet `blockchain_address` to `/get_transactions` endpoint.
> SILA-1889: Added a new search filter param by the wallet blockchain_address to /get_transactions endpoint.

- postman/Sila API v0.2 - Local Signer Server Edition.postman_collection.json
New API to pre-check if the entity qualifies for instant ACH
> SILA-1780: New API to pre-check if entity qualifies for instant ACH

- postman/Sila API v0.2 - Local Signer Server Edition.postman_collection.json
Added default flag to register a wallet endpoint
> SILA-1890 : Added default flag to register a wallet endpoint

- postman/Sila API v0.2 - Local Signer Server Edition.postman_collection.json
Update bank account endpoint(/update_account)
> Feature/SILA-2455: Update bank account endpoint(/update_account)

- postman/Sila API v0.2 - Local Signer Server Edition.postman_collection.json
add /get_payment_methods endpoint
> SILA-2810 add /get_payment_methods

- postman/Sila API v0.2 - Local Signer Server Edition.postman_collection.json
https://sila.atlassian.net/browse/SILA-2811
> SILA-2811: add postman support for /get_payment_methods

- postman/Sila API v0.2 - Local Signer Server Edition.postman_collection.json
Add new endpoint for Retry Webhook
> SILA-3508 Add a new endpoint: /retry_webhook

- postman/Sila API v0.2 - Local Signer Server Edition.postman_collection.json
https://sila.atlassian.net/browse/SILA-3597
> SILA-3597: /create_test_virtual_account_transaction

- postman/Sila API v0.2 - Local Signer Server Edition.postman_collection.json
see https://sila.atlassian.net/browse/SSKI-1 and related grandcentral PR
Adding  device parameter in registration
create new endpoint to add device for registered user
> Sardine-Sila KYC Integration

- postman/Sila API v0.2 - Local Signer Server Edition.postman_collection.json
- postman/SilaSandbox.postman_environment.json
https://sila.atlassian.net/browse/SILA-3538
adding update_virtual_accounts endpoint to postman collection, adding vaccounts-related variables to environment file
> SILA-3538: update_virtual_accounts w/debits & credits

- postman/Sila API v0.2 - Local Signer Server Edition.postman_collection.json
found endpoint request to be incorrect when trying to create a test ACH transaction to fund a new vacct.
> Fix errors in `create_test_virtual_account_ach_transaction`

- postman/Sila API v0.2 - Local Signer Server Edition.postman_collection.json
Deliver virtual account changes into master postman collection
* https://sila.atlassian.net/browse/SILA-1627 - original vAcct epic
* https://sila.atlassian.net/browse/SILA-3695 - vAcct disputes epic
> SILA-1627 - deliver vaccounts changes into master postman collection

- postman/Sila - JWT AuthToken Edition.postman_environment.json
- postman/Sila API v0.2 - JWT OAuth Edition.postman_collection.json
https://sila.atlassian.net/browse/ENGRG-555
> JWT OAuth postman collection

- Dockerfile
- Makefile
- README.md
- requirements.txt
Ticket_URL - https://sila.atlassian.net/browse/ENGRG-737
> Engrg 737 python version upgrade to 3.8.6

- postman/Sila API v0.2 - Local Signer Server Edition.postman_collection.json
update postman collection for Statement Details APIs
https://sila.atlassian.net/browse/SILA-5878
> Sila 5878 postman collection statement

- postman/Sila API v0.2 - Local Signer Server Edition.postman_collection.json
- postman/SilaSandbox.postman_environment.json
https://sila.atlassian.net/browse/ENGRG-933
> ENGRG-933 - add CKO Debit Card Refund endpoint

- requirements.txt
- signerserver/keys.py
https://sila.atlassian.net/browse/ENGRG-2033
> ENGRG-2033 updated packages to fix vulnerabilities.

- Dockerfile
https://sila.atlassian.net/browse/ENGRG-2157
> ENGRG-2157 updated docker image.

- requirements.txt
- signerserver/keys.py
https://sila.atlassian.net/browse/ENGRG-2226
> ENGRG-2226 updated encryption package.

- Dockerfile
https://sila.atlassian.net/browse/ENGRG-2263
> ENGRG-2263 Debian upgrade

- Dockerfile
https://sila.atlassian.net/browse/ENGRG-3018
> ENGRG-3018 upgraded docker image.

- Dockerfile
- README.md
https://sila.atlassian.net/browse/ENGRG-3282
> ENGRG-3282 upgraded python version.

- postman/Sila API v0.2 - Local Signer Server Edition.postman_collection.json
Update URL for update vaccount endpoint in Sila Postman Signer
https://sila.atlassian.net/browse/ENGRG-2172
> ENGRG-2172 Update URL for update vaccount endpoint in Sila Postman Signer
